# Generated by Django 5.2.6 on 2025-10-01 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('qr_image_gcs_path', models.CharField(blank=True, max_length=512)),
                ('qr_image_public_url', models.URLField(blank=True, max_length=1024)),
                ('target_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('READY', 'READY'), ('FAILED', 'FAILED')], db_index=True, default='PENDING', max_length=16)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('user_preferences', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('UPLOADED', 'UPLOADED'), ('AI_REQUESTED', 'AI_REQUESTED'), ('AI_READY', 'AI_READY'), ('DECORATING', 'DECORATING'), ('FINALIZED', 'FINALIZED'), ('FAILED', 'FAILED')], db_index=True, default='CREATED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.qrcode')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='image.style')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ORIGINAL', 'ORIGINAL'), ('AI', 'AI'), ('FINAL', 'FINAL')], db_index=True, max_length=16)),
                ('gcs_path', models.CharField(max_length=512)),
                ('public_url', models.URLField(blank=True, db_index=True, max_length=1024, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('mime', models.CharField(blank=True, max_length=64, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='image.session')),
            ],
        ),
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED')], db_index=True, default='PENDING', max_length=32)),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.imageasset')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='image.session')),
            ],
        ),
        migrations.AddConstraint(
            model_name='imageasset',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'FINAL')), fields=('session', 'kind'), name='uniq_final_per_session'),
        ),
    ]
