# Generated by Django 5.2.6 on 2025-11-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_style_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
